// Shared by the generated landing page and its introductory exercise.
// Scripture quotations are KJV; excerpts are explicitly marked in the interface.
export const PROMISES = [
  {
    id: "prayer", name: "Answered prayer", short: "Ask. Receive?", ref: "Mark 11:24",
    verse: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
    context: "Read Mark 11:20–26. The passage connects prayer with faith and forgiveness. Decide which conditions and audience you think the promise specifies; do not infer them from whether a request succeeds.",
    contextRef: "Mark 11:20-26", related: ["John 14:13-14", "Matthew 7:7-11"],
    question: "What should someone who prays expect to receive?",
    hint: "Does prayer deliver the requested result, improve its chances, or promise something different?",
    outcome: "receiving the requested earthly outcome",
    guaranteed: "The requested outcome will happen when the stated conditions are met.",
    tendency: "Qualifying requests are more likely to be fulfilled than comparable requests without prayer.",
    spiritual: "The promise is spiritual assurance, not a guarantee of the requested earthly outcome.",
    test: "Record specific requests, eligibility conditions, and a meaningful assessment date before learning the outcomes. Keep every result. For a claim of improved chances, compare similar circumstances without targeted prayer.",
    caveat: "A comparison must distinguish prayer from differences in practical help, resources, timing, and ordinary coincidence.",
    suggested: "Which requests qualify, what counts as receiving them, and by when?",
  },
  {
    id: "healing", name: "Healing", short: "Prayer. Recovery?", ref: "James 5:14–15",
    verse: "Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord: And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.",
    context: "Read James 5:13–18. The passage mentions illness, elders, prayer, anointing, forgiveness, and confession. Christians differ over how its language relates bodily restoration and spiritual salvation.",
    contextRef: "James 5:13-18", related: ["1 Peter 2:24"],
    question: "What should a sick person expect after this prayer?",
    hint: "If this means physical healing, which recoveries—and which failures—would count?",
    outcome: "physical recovery following the described prayer",
    guaranteed: "Every sick person meeting the stated conditions will physically recover.",
    tendency: "Those meeting the conditions are more likely to recover than comparable patients.",
    spiritual: "This concerns spiritual restoration, not a promise of physical recovery.",
    test: "Specify qualifying illness, prayer conditions, and the recovery expected by an agreed time. Assess existing, independently documented outcomes and include every eligible case. A probability claim also needs comparable patients and ordinary treatment accounted for.",
    caveat: "This is a reasoning exercise, not a medical experiment. A fair comparison preserves medical care and accounts for treatment, initial severity, and natural recovery.",
    suggested: "What counts as healing, whose prayer qualifies, and when should recovery occur?",
  },
  {
    id: "protection", name: "Protection", short: "Faith. Safety?", ref: "Luke 10:19",
    verse: "Behold, I give unto you power to tread on serpents and scorpions, and over all the power of the enemy: and nothing shall by any means hurt you.",
    context: "Read Luke 10:17–20. Jesus addresses the returning seventy. Whether this assurance extends to all Christians today is a question to settle before proposing a general protection claim.",
    contextRef: "Luke 10:17-20", related: ["Matthew 10:29-31", "Psalm 91:9-12"],
    question: "What protection does this passage promise today?",
    hint: "Is this observable protection from harm, a specific historical assurance, or spiritual security?",
    outcome: "protection from the specified earthly harms",
    guaranteed: "People covered by the promise will be kept from the specified harms.",
    tendency: "People covered by the promise face less of that harm than comparable people.",
    spiritual: "It promises spiritual security, not less physical harm.",
    test: "Define the protected people and the particular harms in advance. Check existing records over an agreed period. If you predict reduced risk, compare people with similar exposure and circumstances.",
    caveat: "Use existing evidence; never expose anyone to danger. A harm outside the claimed scope cannot fairly be counted as a failure.",
    suggested: "Who is covered, against which harms, and for what period?",
  },
  {
    id: "provision", name: "Provision", short: "Trust. Enough?", ref: "Matthew 6:33",
    verse: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    context: "Read Matthew 6:25–34. “These things” refers to the food, drink, and clothing discussed in the passage. This should not silently become a promise of wealth or of every desired possession.",
    contextRef: "Matthew 6:25-34", related: ["Philippians 4:19"],
    question: "What should those who seek God first expect to receive?",
    hint: "Does seeking God secure basic needs, improve the chances, or offer reassurance through hardship?",
    outcome: "having the specified basic needs met",
    guaranteed: "People meeting the conditions will have the promised basic needs met.",
    tendency: "They are more likely to have those needs met than comparable people.",
    spiritual: "It offers assurance through hardship, not a prediction that needs will be met.",
    test: "Specify what seeking first means and which basic needs must be met over an agreed period. Record hardship as well as provision. For an improved-chances claim, compare people with similar income, location, and access to help.",
    caveat: "Community generosity may be part of a religious account of provision. If you claim an additional divine effect, distinguish it from the support people actually receive.",
    suggested: "Which needs are promised, who qualifies, and when would unmet need count?",
  },
  {
    id: "wisdom", name: "Wisdom & guidance", short: "Ask. Discern?", ref: "James 1:5",
    verse: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
    context: "Read James 1:2–8. Wisdom appears in the setting of trials and perseverance; verses 6–8 discuss faith and doubt. Better forecasts are only a fair test if your interpretation actually predicts them.",
    contextRef: "James 1:2-8", related: ["John 14:26"],
    question: "What would receiving wisdom look like?",
    hint: "Can wiser judgment be recognized independently, or does this describe an inward experience?",
    outcome: "the specified improvement in judgment or conduct",
    guaranteed: "Those who ask under the stated conditions will show the promised wisdom.",
    tendency: "They will show wiser judgment more often than comparable people.",
    spiritual: "It concerns inward spiritual understanding, not an independently assessed advantage.",
    test: "First define wisdom in a way faithful to your reading—for example, specific qualities of judgment or conduct. Agree on assessment criteria before observing cases. Where appropriate, use reviewers who do not know who sought divine guidance.",
    caveat: "Wisdom need not mean intelligence or prediction accuracy. A test of the wrong definition tells you little about this interpretation.",
    suggested: "Which qualities count as wisdom, and how could someone else recognize them?",
  },
  {
    id: "prophecy", name: "Prophecy", short: "Foretell. Verify?", ref: "Acts 2:17",
    verse: "And it shall come to pass in the last days, saith God, I will pour out of my Spirit upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams:",
    context: "Read Acts 2:14–21. Peter quotes Joel while explaining Pentecost. Whether prophecy continues today, and whether it means specific prediction rather than inspired speech, both affect what can be tested.",
    contextRef: "Acts 2:14-21", related: ["John 16:13"],
    question: "Does this promise knowledge of future events today?",
    hint: "Would specific predictions outperform ordinary forecasting, or does prophecy mean something else?",
    outcome: "accurate, specific knowledge of future events",
    guaranteed: "Genuine prophecy provides specific predictions that will come true.",
    tendency: "Claimed prophetic predictions are more accurate than ordinary forecasting.",
    spiritual: "Prophecy means inspired spiritual speech, not specific foreknowledge.",
    test: "Record specific predictions before the events, with deadlines and clear success criteria. Retain misses. For an accuracy-advantage claim, compare against informed ordinary forecasts and score without knowing the source.",
    caveat: "The passage does not itself specify that every prophecy predicts an event. Test this only if foreknowledge belongs to the interpretation you affirm.",
    suggested: "Who counts as a prophet before the result, and what would constitute a wrong prediction?",
  },
  {
    id: "character", name: "Transformed character", short: "Believe. Become?", ref: "2 Corinthians 5:17",
    verse: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    context: "Read 2 Corinthians 5:14–21. Paul discusses new creation and reconciliation. Whether this implies measurable changes in behavior, a changed spiritual standing, or both needs to be made explicit.",
    contextRef: "2 Corinthians 5:14-21", related: ["John 13:35", "Galatians 5:22-23"],
    question: "What changes should becoming Christian produce?",
    hint: "Does new life entail observable moral change, a new spiritual status, or both?",
    outcome: "the specified observable change in character",
    guaranteed: "Those in Christ will show the specified observable moral change.",
    tendency: "They are more likely to show that change than comparable people.",
    spiritual: "This promises a new spiritual standing, not a measurable moral improvement.",
    test: "Define observable changes without assuming moral perfection. Examine behavior over an agreed period, using more than self-report. For comparative claims, consider starting behavior, community support, and similar opportunities for change.",
    caveat: "Define who qualifies independently of whether they improve. Excluding every counterexample as “not a real Christian” would make the test circular.",
    suggested: "Which changes, over what period, and how is being “in Christ” identified?",
  },
  {
    id: "health", name: "Health", short: "Devotion. Vitality?", ref: "3 John 1:2",
    verse: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.",
    context: "Read 3 John 1:1–4. This is a greeting addressed to Gaius, phrased as a wish. Consider whether there is a textual basis for treating it as a divine promise to all believers.",
    contextRef: "3 John 1:1-4", related: ["Matthew 8:16-17", "Exodus 23:25"],
    question: "Is this a health promise, or a wish for someone’s wellbeing?",
    hint: "A wish for health and a guarantee of health make very different commitments.",
    outcome: "the specified level of physical health",
    guaranteed: "It promises the specified physical health to people meeting its conditions.",
    tendency: "It promises better health on average than comparable people experience.",
    spiritual: "I take it as spiritual encouragement, without a physical-health prediction.",
    test: "If you read this as a health promise, specify eligible people and the health outcomes expected over time. Use existing records, including illness. Comparative claims need attention to age, lifestyle, income, and access to care.",
    caveat: "Do not turn a personal greeting into a universal guarantee without an argument. This exercise allows you to identify it as a wish rather than a promise.",
    suggested: "Why is this a promise, who receives it, and which health outcomes does it predict?",
  },
  {
    id: "longevity", name: "Long life", short: "Honour. Live longer?", ref: "Ephesians 6:2–3",
    verse: "Honour thy father and mother; (which is the first commandment with promise;) That it may be well with thee, and thou mayest live long on the earth.",
    context: "Read Ephesians 6:1–4 and Exodus 20:12. Paul cites the commandment about honoring parents. Consider the relationship between its original setting and its application in this letter.",
    contextRef: "Ephesians 6:1-4", related: ["Exodus 20:12", "1 Timothy 4:8"],
    question: "What does “live long on the earth” commit this promise to?",
    hint: "Does honoring parents guarantee a long life, improve the odds, or express a general principle?",
    outcome: "the specified length of earthly life",
    guaranteed: "People meeting the conditions will live to the promised old age.",
    tendency: "They are more likely to live longer than comparable people.",
    spiritual: "I read it as fullness of life or future hope, not an earthly lifespan prediction.",
    test: "Define honoring parents and what living long means before consulting lifespan records. If predicting an average advantage, compare similar people while accounting for background, lifestyle, and social support.",
    caveat: "A general tendency differs from a guarantee for each person. Neither should be silently substituted for the other after seeing outcomes.",
    suggested: "What age or lifespan advantage is expected, and whose lives count?",
  },
];

export const bibleLink = (reference) => `https://www.biblegateway.com/passage/?search=${encodeURIComponent(reference)}&version=KJV`;

export function interpretationOptions(promise) {
  return [
    { id: "guarantee", label: "An earthly result is promised", detail: promise.guaranteed },
    { id: "tendency", label: "Better earthly chances are promised", detail: promise.tendency },
    { id: "spiritual", label: "A spiritual meaning, not this earthly result", detail: promise.spiritual },
    { id: "historical", label: "A promise for a particular audience or time", detail: "I do not extend it to people today. A historical claim could still need historical evidence." },
    { id: "not-promise", label: "This is not a promise of that result", detail: "I read it as a wish, instruction, description, or general wisdom—not a divine commitment to this outcome." },
    { id: "unsure", label: "I’m unsure, or my interpretation differs", detail: "Keep this open. You can explain your reading in your own words." },
  ];
}

export const COMMITMENTS = [
  { id: "scope", label: "Identify who qualifies before seeing results", detail: "Conditions such as faith or sincerity need a way to be recognized that does not depend on success." },
  { id: "outcome", label: "Define fulfillment and a fair assessment time", detail: "Decide what should happen and when an outcome can fairly be judged. If no timeframe follows from your reading, explain that limitation." },
  { id: "records", label: "Keep failures in the record", detail: "Include eligible cases that do not produce the expected outcome as well as those that do." },
  { id: "comparison", label: "Use a fair comparison for improved chances", detail: "Compare similar circumstances and account for ordinary explanations; a favorable outcome alone does not establish divine intervention." },
];

export const FAILURE_OPTIONS = [
  { id: "yes", label: "Yes. That would count against my reading.", detail: "The test must actually match my interpretation and be strong enough to assess what it predicts." },
  { id: "conditions", label: "Only if further conditions were met.", detail: "Those conditions still need to be specified and checked independently of the result." },
  { id: "no", label: "No. No earthly result could count against it.", detail: "I would retain this interpretation whatever the observed outcome." },
  { id: "unsure", label: "I haven’t decided.", detail: "Leave the standard for failure unresolved for now." },
];
