// Shared by the generated landing page and its introductory exercise.
// Scripture quotations are KJV; excerpts are explicitly marked in the interface.
export const PROMISES = [
  {
    id: "prayer", name: "Answered prayer", short: "Ask. Receive?", ref: "Mark 11:24",
    verse: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
    context: "Read Mark 11:20–26. The passage connects prayer with faith and forgiveness. Decide which conditions and audience you think the promise specifies; do not infer them from whether a request succeeds.",
    contextRef: "Mark 11:20-26", related: ["John 14:13-14", "Matthew 7:7-11"],
    question: "What do you believe this verse promises to someone who prays?",
    hint: "Does prayer deliver the requested result, improve its chances, or promise something different?",
    outcome: "receiving the requested earthly outcome",
    guaranteed: { label: "Every qualifying prayer receives what was requested.", detail: "God guarantees the requested result whenever the passage’s conditions are met. This applies to prayer today." },
    tendency: { label: "Prayer improves the odds of receiving what was requested.", detail: "God promises a higher success rate than comparable requests without prayer today. Individual prayers can go unfulfilled." },
    spiritual: { label: "God promises spiritual assurance only.", detail: "This applies to believers today, but promises neither the requested earthly result nor a better chance of receiving it." },
    historical: "The promised answer applied only to the people or period originally addressed. It makes no promise about prayers today.",
    notPromise: "This passage teaches or encourages prayer without committing God to any result, earthly or spiritual.",
    test: "Record specific requests, eligibility conditions, and a meaningful assessment date before learning the outcomes. Keep every result. For a claim of improved chances, compare similar circumstances without targeted prayer.",
    caveat: "A comparison must distinguish prayer from differences in practical help, resources, timing, and ordinary coincidence.",
    suggested: "Which requests qualify, what counts as receiving them, and by when?",
  },
  {
    id: "healing", name: "Healing", short: "Prayer. Recovery?", ref: "James 5:14–15",
    verse: "Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord: And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.",
    context: "Read James 5:13–18. The passage mentions illness, elders, prayer, anointing, forgiveness, and confession. Christians differ over how its language relates bodily restoration and spiritual salvation.",
    contextRef: "James 5:13-18", related: ["1 Peter 2:24"],
    question: "What do you believe this passage promises to a sick person?",
    hint: "If this means physical healing, which recoveries—and which failures—would count?",
    outcome: "physical recovery following the described prayer",
    guaranteed: { label: "Every sick person who meets the conditions will physically recover.", detail: "God guarantees recovery after the prayer described here. This applies to sick people today." },
    tendency: { label: "This prayer improves a sick person’s chance of recovery.", detail: "God promises a higher recovery rate than among comparable patients without this prayer today. Some patients may not recover." },
    spiritual: { label: "God promises spiritual restoration only.", detail: "This applies today, but promises neither physical recovery nor an improved chance of recovery." },
    historical: "The healing promise applied only to the people or period originally addressed. It makes no healing promise to patients today.",
    notPromise: "This passage gives instructions for caring and praying for the sick without committing God to any result, earthly or spiritual.",
    test: "Specify qualifying illness, prayer conditions, and the recovery expected by an agreed time. Assess existing, independently documented outcomes and include every eligible case. A probability claim also needs comparable patients and ordinary treatment accounted for.",
    caveat: "This is a reasoning exercise, not a medical experiment. A fair comparison preserves medical care and accounts for treatment, initial severity, and natural recovery.",
    suggested: "What counts as healing, whose prayer qualifies, and when should recovery occur?",
  },
  {
    id: "protection", name: "Protection", short: "Faith. Safety?", ref: "Luke 10:19",
    verse: "Behold, I give unto you power to tread on serpents and scorpions, and over all the power of the enemy: and nothing shall by any means hurt you.",
    context: "Read Luke 10:17–20. Jesus addresses the returning seventy. Whether this assurance extends to all Christians today is a question to settle before proposing a general protection claim.",
    contextRef: "Luke 10:17-20", related: ["Matthew 10:29-31", "Psalm 91:9-12"],
    question: "What protection do you believe this passage promises?",
    hint: "Is this observable protection from harm, a specific historical assurance, or spiritual security?",
    outcome: "protection from the specified earthly harms",
    guaranteed: { label: "Everyone covered by this promise will escape the specified harms.", detail: "God guarantees protection from those harms to qualifying people today. No covered person will suffer them." },
    tendency: { label: "People covered by this promise are less likely to suffer those harms.", detail: "Today, God promises lower risk than for equally exposed people outside the promise. Some covered people may still be harmed." },
    spiritual: { label: "God promises spiritual security only.", detail: "This applies today, but promises neither physical safety nor a lower risk of physical harm." },
    historical: "Jesus promised protection only to the people or period originally addressed. I do not extend that promise to Christians today.",
    notPromise: "Jesus uses reassurance or imagery here without committing God to protect anyone, physically or spiritually.",
    test: "Define the protected people and the particular harms in advance. Check existing records over an agreed period. If you predict reduced risk, compare people with similar exposure and circumstances.",
    caveat: "Use existing evidence; never expose anyone to danger. A harm outside the claimed scope cannot fairly be counted as a failure.",
    suggested: "Who is covered, against which harms, and for what period?",
  },
  {
    id: "provision", name: "Provision", short: "Trust. Enough?", ref: "Matthew 6:33",
    verse: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    context: "Read Matthew 6:25–34. “These things” refers to the food, drink, and clothing discussed in the passage. This should not silently become a promise of wealth or of every desired possession.",
    contextRef: "Matthew 6:25-34", related: ["Philippians 4:19"],
    question: "What do you believe God promises to those who seek him first?",
    hint: "Does seeking God secure basic needs, improve the chances, or offer reassurance through hardship?",
    outcome: "having the specified basic needs met",
    guaranteed: { label: "Everyone who meets the conditions will receive food, drink, and clothing.", detail: "God guarantees these basic necessities to those who seek him first today. The promise allows no qualifying person to go without them." },
    tendency: { label: "Seeking God first improves the chances of having basic needs met.", detail: "Today, God promises better odds than for otherwise similar people who do not seek him first. Some qualifying people may still lack necessities." },
    spiritual: { label: "God promises spiritual assurance through hardship only.", detail: "This applies today, but promises neither that basic needs will be met nor a better chance of meeting them." },
    historical: "The provision promise applied only to the people or period originally addressed. It makes no promise of provision to people today.",
    notPromise: "This passage encourages trust and right priorities without committing God to provide any earthly or spiritual benefit.",
    test: "Specify what seeking first means and which basic needs must be met over an agreed period. Record hardship as well as provision. For an improved-chances claim, compare people with similar income, location, and access to help.",
    caveat: "Community generosity may be part of a religious account of provision. If you claim an additional divine effect, distinguish it from the support people actually receive.",
    suggested: "Which needs are promised, who qualifies, and when would unmet need count?",
  },
  {
    id: "wisdom", name: "Wisdom & guidance", short: "Ask. Discern?", ref: "James 1:5",
    verse: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
    context: "Read James 1:2–8. Wisdom appears in the setting of trials and perseverance; verses 6–8 discuss faith and doubt. Better forecasts are only a fair test if your interpretation actually predicts them.",
    contextRef: "James 1:2-8", related: ["John 14:26"],
    question: "What wisdom do you believe God commits to giving?",
    hint: "Can wiser judgment be recognized independently, or does this describe an inward experience?",
    outcome: "the specified improvement in judgment or conduct",
    guaranteed: { label: "Everyone who asks as required will show an observable gain in wisdom.", detail: "God guarantees a recognizable improvement in judgment or conduct to each qualifying person today. What counts as wisdom must be defined beforehand." },
    tendency: { label: "Asking God makes observable gains in wisdom more likely.", detail: "God promises improvement more often than among comparable people who do not ask today. Some qualifying people may show no improvement." },
    spiritual: { label: "God promises inward spiritual understanding only.", detail: "This applies today, but promises no improvement in judgment or conduct that an independent observer could assess." },
    historical: "The wisdom promise applied only to the people or period originally addressed. It makes no promise of wisdom to people today.",
    notPromise: "This passage encourages people to seek wisdom without committing God to grant either observable or inward wisdom.",
    test: "First define wisdom in a way faithful to your reading—for example, specific qualities of judgment or conduct. Agree on assessment criteria before observing cases. Where appropriate, use reviewers who do not know who sought divine guidance.",
    caveat: "Wisdom need not mean intelligence or prediction accuracy. A test of the wrong definition tells you little about this interpretation.",
    suggested: "Which qualities count as wisdom, and how could someone else recognize them?",
  },
  {
    id: "prophecy", name: "Prophecy", short: "Foretell. Verify?", ref: "Acts 2:17",
    verse: "And it shall come to pass in the last days, saith God, I will pour out of my Spirit upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams:",
    context: "Read Acts 2:14–21. Peter quotes Joel while explaining Pentecost. Whether prophecy continues today, and whether it means specific prediction rather than inspired speech, both affect what can be tested.",
    contextRef: "Acts 2:14-21", related: ["John 16:13"],
    question: "What do you believe this passage promises about prophecy?",
    hint: "Would specific predictions outperform ordinary forecasting, or does prophecy mean something else?",
    outcome: "accurate, specific knowledge of future events",
    guaranteed: { label: "Every prediction from a qualifying prophet today will come true.", detail: "God promises specific, accurate foreknowledge today. Who qualifies as a prophet must be settled before checking the predictions." },
    tendency: { label: "Prophets today predict events more accurately than ordinary forecasters.", detail: "God promises an accuracy advantage over comparable informed forecasts. Individual prophetic predictions may be wrong." },
    spiritual: { label: "God promises inspired spiritual speech only.", detail: "This applies today, but promises neither knowledge of future events nor better predictions than ordinary forecasting." },
    historical: "The promise of prophecy applied only to an earlier audience or period. It does not promise prophetic gifts to people today.",
    notPromise: "This passage uses religious imagery or description without committing God to grant prophecy or inspired speech.",
    test: "Record specific predictions before the events, with deadlines and clear success criteria. Retain misses. For an accuracy-advantage claim, compare against informed ordinary forecasts and score without knowing the source.",
    caveat: "The passage does not itself specify that every prophecy predicts an event. Test this only if foreknowledge belongs to the interpretation you affirm.",
    suggested: "Who counts as a prophet before the result, and what would constitute a wrong prediction?",
  },
  {
    id: "character", name: "Transformed character", short: "Believe. Become?", ref: "2 Corinthians 5:17",
    verse: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    context: "Read 2 Corinthians 5:14–21. Paul discusses new creation and reconciliation. Whether this implies measurable changes in behavior, a changed spiritual standing, or both needs to be made explicit.",
    contextRef: "2 Corinthians 5:14-21", related: ["John 13:35", "Galatians 5:22-23"],
    question: "What change do you believe this verse promises to those in Christ?",
    hint: "Does new life entail observable moral change, a new spiritual status, or both?",
    outcome: "the specified observable change in character",
    guaranteed: { label: "Every person who is “in Christ” will show observable moral improvement.", detail: "God guarantees the defined improvement in each qualifying person today. This need not mean moral perfection." },
    tendency: { label: "Being “in Christ” makes observable moral improvement more likely.", detail: "God promises improvement more often than among comparable people who are not “in Christ” today. Some qualifying people may not improve." },
    spiritual: { label: "God promises a new spiritual standing only.", detail: "This applies today, but promises neither observable moral improvement nor a greater chance of improvement." },
    historical: "The new-creation promise applied only to the people or period originally addressed. I do not extend it to Christians today.",
    notPromise: "This passage describes Christian identity or an ideal without committing God to change anyone’s behavior or spiritual standing.",
    test: "Define observable changes without assuming moral perfection. Examine behavior over an agreed period, using more than self-report. For comparative claims, consider starting behavior, community support, and similar opportunities for change.",
    caveat: "Define who qualifies independently of whether they improve. Excluding every counterexample as “not a real Christian” would make the test circular.",
    suggested: "Which changes, over what period, and how is being “in Christ” identified?",
  },
  {
    id: "health", name: "Health", short: "Devotion. Vitality?", ref: "3 John 1:2",
    verse: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.",
    context: "Read 3 John 1:1–4. This is a greeting addressed to Gaius, phrased as a wish. Consider whether there is a textual basis for treating it as a divine promise to all believers.",
    contextRef: "3 John 1:1-4", related: ["Matthew 8:16-17", "Exodus 23:25"],
    question: "Do you believe this verse makes a divine health promise?",
    hint: "A wish for health and a guarantee of health make very different commitments.",
    outcome: "the specified level of physical health",
    guaranteed: { label: "Everyone who meets the conditions will have the promised physical health.", detail: "God guarantees a defined level of health to each qualifying person today. That level must be specified before checking health records." },
    tendency: { label: "People who meet the conditions will have better physical health on average.", detail: "Today, God promises better average health than among otherwise similar people who do not meet the conditions. Some qualifying people may still be seriously ill." },
    spiritual: { label: "God promises spiritual well-being only.", detail: "This applies today, but promises neither physical health nor better health on average." },
    historical: "John conveys a divine health promise for Gaius or his time only. I do not extend that promise to people today.",
    notPromise: "John expresses a wish for Gaius’s well-being. A wish does not commit God to provide health or any other result.",
    test: "If you read this as a health promise, specify eligible people and the health outcomes expected over time. Use existing records, including illness. Comparative claims need attention to age, lifestyle, income, and access to care.",
    caveat: "Do not turn a personal greeting into a universal guarantee without an argument. This exercise allows you to identify it as a wish rather than a promise.",
    suggested: "Why is this a promise, who receives it, and which health outcomes does it predict?",
  },
  {
    id: "longevity", name: "Long life", short: "Honour. Live longer?", ref: "Ephesians 6:2–3",
    verse: "Honour thy father and mother; (which is the first commandment with promise;) That it may be well with thee, and thou mayest live long on the earth.",
    context: "Read Ephesians 6:1–4 and Exodus 20:12. Paul cites the commandment about honoring parents. Consider the relationship between its original setting and its application in this letter.",
    contextRef: "Ephesians 6:1-4", related: ["Exodus 20:12", "1 Timothy 4:8"],
    question: "What do you believe “live long on the earth” promises?",
    hint: "Does honoring parents guarantee a long life, improve the odds, or express a general principle?",
    outcome: "the specified length of earthly life",
    guaranteed: { label: "Everyone who honors their parents as required will reach old age.", detail: "God guarantees a long earthly life to each qualifying person today. What counts as old age must be settled before checking lifespans." },
    tendency: { label: "People who honor their parents will live longer on average.", detail: "Today, God promises a longer average lifespan than for otherwise similar people who do not honor their parents. Some qualifying people may still die young." },
    spiritual: { label: "God promises spiritual fullness of life only.", detail: "This applies today, but promises neither reaching old age nor a longer average earthly lifespan." },
    historical: "The long-life promise applied only to the people or period originally addressed. It makes no lifespan promise to people today.",
    notPromise: "This passage offers a general principle about honoring parents without committing God to a longer life or any spiritual benefit.",
    test: "Define honoring parents and what living long means before consulting lifespan records. If predicting an average advantage, compare similar people while accounting for background, lifestyle, and social support.",
    caveat: "A general tendency differs from a guarantee for each person. Neither should be silently substituted for the other after seeing outcomes.",
    suggested: "What age or lifespan advantage is expected, and whose lives count?",
  },
];

export const bibleLink = (reference) => `https://www.biblegateway.com/passage/?search=${encodeURIComponent(reference)}&version=KJV`;

export function interpretationOptions(promise) {
  return [
    { id: "guarantee", ...promise.guaranteed },
    { id: "tendency", ...promise.tendency },
    { id: "spiritual", ...promise.spiritual },
    { id: "historical", label: "This was a promise for the past only.", detail: promise.historical },
    { id: "not-promise", label: "This passage makes no divine promise.", detail: promise.notPromise },
    { id: "other", label: "I believe this passage makes a different claim.", detail: "I will state the claim I actually affirm and whether evidence could count against it." },
    { id: "unsure", label: "I have not settled what this passage promises.", detail: "Record my answer as unresolved. This does not count as a commitment; I still need to state what I believe." },
  ];
}

export const COMMITMENTS = [
  { id: "scope", label: "I will define who qualifies before checking the results.", detail: "Faith, sincerity, and other conditions must be checked independently. A failed outcome alone cannot make someone ineligible." },
  { id: "outcome", label: "I will specify the expected result and the deadline in advance.", detail: "State what must happen and by when. If my reading supplies no assessable deadline, I will leave this unchecked and explain why." },
  { id: "records", label: "I will count every qualifying case, including failures.", detail: "I will keep unsuccessful cases in the record and apply the same rules to successes and failures." },
  { id: "comparison", label: "I will compare otherwise similar groups.", detail: "I will specify the expected advantage and account for differences such as treatment, resources, or support. Favorable outcomes alone cannot establish divine action." },
];

export const FAILURE_OPTIONS = [
  { id: "yes", label: "That failure would be evidence against my interpretation.", detail: "I would lower my confidence in this reading, even if I did not reject it outright." },
  { id: "conditions", label: "I cannot judge until I specify the conditions.", detail: "I still need to define who qualifies and what would count as failure. I must settle those conditions before checking results." },
  { id: "no", label: "No observed failure could count against my interpretation.", detail: "I would retain this reading regardless of the results, even if the test met all the conditions I had specified." },
  { id: "unsure", label: "I have not decided whether failure would count against it.", detail: "I have not chosen a standard for accepting evidence against this interpretation." },
];
